[workspace]
resolver = "2"
members = ["cgol_bevy"]

[workspace.dependencies]
bevy = { version = "0.17.3", features = ["dynamic_linking"] }
clap = { version = "4.3.14", features = ["derive"] }
dashmap = { version = "6.1.0", features = ["rayon"] }

# Development tools managed by cargo-run-bin
cargo-autoinherit = "0.1.6"
cargo-run-bin = "1.7.2"

[workspace.metadata.bin]
cargo-autoinherit = { version = "0.1.6" }

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
