default:
    @just --list

# Run pre-commit hooks on all files, including autoformatting
pre-commit-all:
    pre-commit run --all-files

# Run 'cargo run' on the project
run *ARGS:
    cargo run {{ARGS}}

# Run 'bacon' to run the project (auto-recompiles)
watch *ARGS:
	bacon --job run -- -- {{ ARGS }}

# Install development tools using cargo-run-bin
install-tools:
    cargo bin --install

# Run cargo-autoinherit to manage workspace inheritance
autoinherit:
    cargo autoinherit
